import React, { useState } from "react";
import {
  View,
  Text,
  Pressable,
  Image,
  useWindowDimensions,
  Platform,
  SafeAreaView,
} from "react-native";
import stylePadrao from "../styles/stylesDefault";
import styleHome from "../styles/stylesHome";

function CRUDFirebase(){

    return(
        <SafeAreaView style={styleHome.fixCinza}>
            <View>

                

            </View>
        </SafeAreaView>
    );
}